function vX = vBlobX(x,y,pVortex,gamma,epsilon)
% vBlobX computes the x component of induced velocity generated by vortex
% of circulation gamma, located at pVortex and core spreading epsilon

    vX = -(gamma./(2*pi*(eps+((x-pVortex(1)).^2) + ((y-pVortex(2)).^2)))).*...
          (y-pVortex(2)).*(1-exp(-(((x-pVortex(1)).^2) + ((y-pVortex(2)).^2))/(2*epsilon*epsilon)));
end
