function vY = vBlobY(x,y,pVortex,gamma,epsilon)
% vBlobY computes the y component of induced velocity generated by vortex
% of circulation gamma, located at pVortex and core spreading epsilon

    vY = (gamma./(2*pi*(eps+((x-pVortex(1)).^2) + ((y-pVortex(2)).^2)))).*...
         (x-pVortex(1)).*(1-exp(-(((x-pVortex(1)).^2) + ((y-pVortex(2)).^2))/(2*epsilon*epsilon)));
end